// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Wizard":return img`
........ff....................
.......ffff...................
......ffffff..................
......ffffff..................
.....ffffffff.................
.....ffffffff.................
...fffffffffffff..............
......eeeeeee.................
..5...efefeee.................
.525..eeeeeee.................
..5...e11eeee.................
..e....eeeee..................
..e...cccccc..................
..e..ccccccc..................
..e..ccccccc..................
..e..cccbbccc.................
..e..ccbbbccc.................
..e.bbbbbbccc.................
..bbbbbbbccccc................
..bbbccccccccc................
..e..cccccccccc...............
..e..cccccccccc...............
..e..ccccccccccc..............
..e..ccccccccccc..............
..e...ccc.ccc.................
..e...ccc.ccc.................
..e...ee..ee..................
....ffff.fff..................
....ffff.fff..................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
